public class Biggest {
    public biggest()
    {
integer x=1,y=77,z=38;
    if(x>y)
    {
        if(x>z)
        {
            system.debug('the greater no. X is='+x);
           
        }else
        {
            system.debug('the greater no. Z is='+z);
        }
   }
    else 
 {
     if(y>z)
    {
                system.debug('the greater no. Y is='+y);
    }
    else
    {
      system.debug('the greater no. Z is='+z);      
    
    }
  
 }
}
}